In [34]:
import cv2
import numpy as np

img = cv2.imread ( "test1.png" ) 
#Initialize the slic item, the average superpixel size is 20 (default is 10), and the smoothing factor is 20 
slic = cv2.ximgproc.createSuperpixelSLIC( img , region_size = 100 , ruler =  20.0 )  
slic.iterate( 10 )      
#Number of iterations, the larger the effect, the better 
mask_slic = slic.getLabelContourMask( )  
#Get Mask, super pixel edge Mask==1 
label_slic = slic.getLabels( )         # Get the superpixel tag 
number_slic = slic.getNumberOfSuperpixels( )   # obtain super pixel number 
mask_inv_slic = cv2.bitwise_not( mask_slic )   
img_slic = cv2.bitwise_and( img , img , mask = mask_inv_slic )  # drawn over the pixel boundary on the original 

In [33]:
for range

[[  1   1   1 ...  29  29  29]
 [  1   1   1 ...  29  29  29]
 [  1   1   1 ...  29  29  29]
 ...
 [300 300 300 ... 299 299 299]
 [300 300 300 ... 299 329 329]
 [300 300 300 ... 329 329 329]]


In [15]:
print(img.shape)

(3024, 3024, 3)


In [ ]:
cv2.imshow( "img_slic" , img_slic ) 
cv2.waitKey( ) 
cv2.destroyAllWindows( )